window_maximized = true
screen_h = 1046
screen_w = 1920
enable_damage = true
creative_mode = false
mainmenu_last_selected_world = 1
dpi_change_notifier = 4
menu_last_game = Terrixa
free_move = true
fast_move = true
noclip = true
address = 84.247.132.141
maintab_LAST = local
server_announce = false
remote_port = 40002
name = ZackXDev

enable_fog = false
window_title = Terrixa
fullscreen = true
