title       = Terrixa
description = A basic exploration, mining, crafting, and building, sandbox game with no NPCs, monsters, or animals. Terrixa is usually used with mods added, and many mods are available for this game. Crafted and maintained by the Terrixa team.
min_minetest_version = 5.8
textdomain = game_description

